//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: sensor.proto
import com.development.sensor.SensorOuterClass

@kotlin.jvm.JvmName("-initializetYPEROTATIONVECTOR")
inline fun tYPEROTATIONVECTOR(block: TYPE_ROTATION_VECTORKt.Dsl.() -> kotlin.Unit): SensorOuterClass.TYPE_ROTATION_VECTOR =
  TYPE_ROTATION_VECTORKt.Dsl._create(SensorOuterClass.TYPE_ROTATION_VECTOR.newBuilder()).apply { block() }._build()
/**
 * ```
 *values[0]: x*sin(θ/2)
 *values[1]: y*sin(θ/2)
 *values[2]: z*sin(θ/2)
 *values[3]: cos(θ/2)
 *values[4]: estimated heading Accuracy (in radians) (-1 if unavailable)
 * ```
 *
 * Protobuf type `TYPE_ROTATION_VECTOR`
 */
object TYPE_ROTATION_VECTORKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: SensorOuterClass.TYPE_ROTATION_VECTOR.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: SensorOuterClass.TYPE_ROTATION_VECTOR.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): SensorOuterClass.TYPE_ROTATION_VECTOR = _builder.build()

    /**
     * `double x = 1;`
     */
    var x: kotlin.Double
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * `double x = 1;`
     */
    fun clearX() {
      _builder.clearX()
    }

    /**
     * `double y = 2;`
     */
    var y: kotlin.Double
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * `double y = 2;`
     */
    fun clearY() {
      _builder.clearY()
    }

    /**
     * `double z = 3;`
     */
    var z: kotlin.Double
      @JvmName("getZ")
      get() = _builder.getZ()
      @JvmName("setZ")
      set(value) {
        _builder.setZ(value)
      }
    /**
     * `double z = 3;`
     */
    fun clearZ() {
      _builder.clearZ()
    }

    /**
     * `double cos = 4;`
     */
    var cos: kotlin.Double
      @JvmName("getCos")
      get() = _builder.getCos()
      @JvmName("setCos")
      set(value) {
        _builder.setCos(value)
      }
    /**
     * `double cos = 4;`
     */
    fun clearCos() {
      _builder.clearCos()
    }

    /**
     * `double accuracy = 5;`
     */
    var accuracy: kotlin.Double
      @JvmName("getAccuracy")
      get() = _builder.getAccuracy()
      @JvmName("setAccuracy")
      set(value) {
        _builder.setAccuracy(value)
      }
    /**
     * `double accuracy = 5;`
     */
    fun clearAccuracy() {
      _builder.clearAccuracy()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun SensorOuterClass.TYPE_ROTATION_VECTOR.copy(block: TYPE_ROTATION_VECTORKt.Dsl.() -> kotlin.Unit): SensorOuterClass.TYPE_ROTATION_VECTOR =
  TYPE_ROTATION_VECTORKt.Dsl._create(this.toBuilder()).apply { block() }._build()

